# SPDX-FileCopyrightText: 2026 GovDesk-Mitwirkende
#
# SPDX-License-Identifier: EUPL-1.2

"""OIDC-Identitaeten

Revision: 184e09a2d971
Vorgänger: 554b1fe036e7
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '184e09a2d971'
down_revision: str | None = '554b1fe036e7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oidc_identities',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('issuer', sa.String(length=500), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('email_at_link', sa.String(length=320), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_oidc_identities_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_oidc_identities')),
    sa.UniqueConstraint('issuer', 'subject', name=op.f('uq_oidc_identities_issuer'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('oidc_identities')
    # ### end Alembic commands ###
