# SPDX-FileCopyrightText: 2026 GovDesk-Mitwirkende
#
# SPDX-License-Identifier: EUPL-1.2

"""Crawler-Tabellen

Revision: 554b1fe036e7
Vorgänger: e5b35d60a5c5
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '554b1fe036e7'
down_revision: str | None = 'e5b35d60a5c5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crawl_sources',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('collection_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('start_url', sa.Text(), nullable=False),
    sa.Column('mode', sa.Enum('single', 'recursive', name='crawl_mode'), nullable=False),
    sa.Column('max_depth', sa.Integer(), nullable=False),
    sa.Column('max_pages', sa.Integer(), nullable=False),
    sa.Column('allowed_domains', postgresql.ARRAY(sa.String(length=255)), nullable=True),
    sa.Column('url_include_pattern', sa.String(length=500), nullable=True),
    sa.Column('url_exclude_pattern', sa.String(length=500), nullable=True),
    sa.Column('recrawl_interval_hours', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], name=op.f('fk_crawl_sources_collection_id_collections'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_crawl_sources_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_crawl_sources'))
    )
    op.create_index(op.f('ix_crawl_sources_project_id'), 'crawl_sources', ['project_id'], unique=False)
    op.create_table('crawl_jobs',
    sa.Column('crawl_source_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'done', 'failed', 'cancelled', name='crawl_job_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('pages_fetched', sa.Integer(), nullable=False),
    sa.Column('pages_ingested', sa.Integer(), nullable=False),
    sa.Column('pages_skipped', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['crawl_source_id'], ['crawl_sources.id'], name=op.f('fk_crawl_jobs_crawl_source_id_crawl_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_crawl_jobs'))
    )
    op.create_index(op.f('ix_crawl_jobs_crawl_source_id'), 'crawl_jobs', ['crawl_source_id'], unique=False)
    op.create_table('crawl_pages',
    sa.Column('crawl_source_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('url_hash', sa.String(length=64), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('last_fetched_at', sa.DateTime(), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['crawl_source_id'], ['crawl_sources.id'], name=op.f('fk_crawl_pages_crawl_source_id_crawl_sources'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_crawl_pages_document_id_documents'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_crawl_pages')),
    sa.UniqueConstraint('crawl_source_id', 'url_hash', name=op.f('uq_crawl_pages_crawl_source_id'))
    )
    op.create_index(op.f('ix_crawl_pages_crawl_source_id'), 'crawl_pages', ['crawl_source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crawl_pages_crawl_source_id'), table_name='crawl_pages')
    op.drop_table('crawl_pages')
    op.drop_index(op.f('ix_crawl_jobs_crawl_source_id'), table_name='crawl_jobs')
    op.drop_table('crawl_jobs')
    op.drop_index(op.f('ix_crawl_sources_project_id'), table_name='crawl_sources')
    op.drop_table('crawl_sources')
    # ### end Alembic commands ###
