# SPDX-FileCopyrightText: 2026 GovDesk-Mitwirkende
#
# SPDX-License-Identifier: EUPL-1.2

"""Collections + documents.collection_id

Revision: 66edfb93ce63
Vorgänger: 5a032103c88b
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '66edfb93ce63'
down_revision: str | None = '5a032103c88b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collections',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_collections_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_collections')),
    sa.UniqueConstraint('project_id', 'name', name=op.f('uq_collections_project_id'))
    )
    op.create_index(op.f('ix_collections_project_id'), 'collections', ['project_id'], unique=False)
    op.add_column('documents', sa.Column('collection_id', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_documents_collection_id_collections'), 'documents', 'collections', ['collection_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_documents_collection_id_collections'), 'documents', type_='foreignkey')
    op.drop_column('documents', 'collection_id')
    op.drop_index(op.f('ix_collections_project_id'), table_name='collections')
    op.drop_table('collections')
    # ### end Alembic commands ###
