# SPDX-FileCopyrightText: 2026 GovDesk-Mitwirkende
#
# SPDX-License-Identifier: EUPL-1.2

"""Chat-Configs

Revision: bcce3502e4ab
Vorgänger: 66edfb93ce63
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'bcce3502e4ab'
down_revision: str | None = '66edfb93ce63'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_configs',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('top_k', sa.Integer(), nullable=False),
    sa.Column('rerank_enabled', sa.Boolean(), nullable=False),
    sa.Column('collection_ids', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_chat_configs_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_configs'))
    )
    op.create_index(op.f('ix_chat_configs_project_id'), 'chat_configs', ['project_id'], unique=False)
    op.add_column('chat_sessions', sa.Column('chat_config_id', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_chat_sessions_chat_config_id_chat_configs'), 'chat_sessions', 'chat_configs', ['chat_config_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_chat_sessions_chat_config_id_chat_configs'), 'chat_sessions', type_='foreignkey')
    op.drop_column('chat_sessions', 'chat_config_id')
    op.drop_index(op.f('ix_chat_configs_project_id'), table_name='chat_configs')
    op.drop_table('chat_configs')
    # ### end Alembic commands ###
