# SPDX-FileCopyrightText: 2026 GovDesk-Mitwirkende
#
# SPDX-License-Identifier: EUPL-1.2

"""connector tabellen

Revision: ec2aabd8009a
Vorgänger: a1c7f2e9b3d4
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'ec2aabd8009a'
down_revision: str | None = 'a1c7f2e9b3d4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Neuer Wert für das bestehende document_source-Enum (von Autogenerate nicht
    # erkannt). PG17 erlaubt ADD VALUE innerhalb der Transaktion, solange der Wert
    # nicht im selben Migrationslauf verwendet wird.
    op.execute("ALTER TYPE document_source ADD VALUE IF NOT EXISTS 'connector'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connector_sources',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('collection_id', sa.UUID(), nullable=True),
    sa.Column('connector_type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sync_interval_hours', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], name=op.f('fk_connector_sources_collection_id_collections'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_connector_sources_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_connector_sources'))
    )
    op.create_index(op.f('ix_connector_sources_connector_type'), 'connector_sources', ['connector_type'], unique=False)
    op.create_index(op.f('ix_connector_sources_project_id'), 'connector_sources', ['project_id'], unique=False)
    op.create_table('connector_items',
    sa.Column('connector_source_id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(length=200), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connector_source_id'], ['connector_sources.id'], name=op.f('fk_connector_items_connector_source_id_connector_sources'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_connector_items_document_id_documents'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_connector_items')),
    sa.UniqueConstraint('connector_source_id', 'external_id', name=op.f('uq_connector_items_connector_source_id'))
    )
    op.create_index(op.f('ix_connector_items_connector_source_id'), 'connector_items', ['connector_source_id'], unique=False)
    op.create_table('connector_jobs',
    sa.Column('connector_source_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'done', 'failed', 'cancelled', name='connector_job_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('items_found', sa.Integer(), nullable=False),
    sa.Column('items_ingested', sa.Integer(), nullable=False),
    sa.Column('items_skipped', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connector_source_id'], ['connector_sources.id'], name=op.f('fk_connector_jobs_connector_source_id_connector_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_connector_jobs'))
    )
    op.create_index(op.f('ix_connector_jobs_connector_source_id'), 'connector_jobs', ['connector_source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_connector_jobs_connector_source_id'), table_name='connector_jobs')
    op.drop_table('connector_jobs')
    op.drop_index(op.f('ix_connector_items_connector_source_id'), table_name='connector_items')
    op.drop_table('connector_items')
    op.drop_index(op.f('ix_connector_sources_project_id'), table_name='connector_sources')
    op.drop_index(op.f('ix_connector_sources_connector_type'), table_name='connector_sources')
    op.drop_table('connector_sources')
    # ### end Alembic commands ###
